baseurl: "/jmpweb"
url: "http://jmparsons.github.io"

title: JMParsons
description: Professional HTML5, Javascript, Scala, iOS, and Android Developer.

sass:
  sass_dir: "/assets/css"
  style: :compressed

paginate: 1
paginate_path: "/blog/page:num/"
permalink: /blog/:title

gems:
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
